$schema: "https://json-schema.org/draft/2020-12/schema"
title: cfClone Pipeline Schema
description: Snakemake configuration file for cfClone pipeline
type: object
properties:
  out_dir:
    type: string
    minLength: 1
    description: Path to output directory
  pipeline_dir:
    type: string
    minLength: 1
    description: Path to pipeline working directory

  clone_filter_file:
    type: string
    minLength: 1
    description: Path to file with which clones to keep
  hapclone_data_file:
    type: string
    minLength: 1
    description: Path to single cell data stored in hdf5 file
  hapclone_results_file:
    type: string
    minProperties: 1
    description: Path to HapClone tsv results file
  snp_file:
    type: string
    minProperties: 1
    description: Path to file with patient SNP calls in BCF/VCF format with index

  coverage:
    type: array
    contains:
      "type": "number"
    minContains: 1
    description: List of coverage values to test
  tumour_content:
    type: array
    contains:
      "type": "number"
    minContains: 1
    description: List of tumour content values to test
  num_model_replicates:
    type: integer
    minimum: 1
    default: 1
    description: Number of replicates per setting of coverage and tumour content
  clone_prevalences:
    type: string
    minLength: 1
    description: List of paths to files with specified clone prevalences to use for simulation
  num_bins:
    type: ["integer", "string"]
    minimum: 0
    default: [0]
    description: Number of bins to sample for inference. Default 0 uses all bins
  read_length:
    type: integer
    default: 150
    description: Read length of data used for scWGS sequencing


  num_chains:
    type: integer
    minimum: 1
    default: 16
    description: Number of parallel tempering chains used for reference distribution
  num_chains_vi:
    type: integer
    minimum: 1
    default: 8
    description: Number of parallel tempering chains used for variational distribution
  num_rounds:
    type: integer
    minimum: 1
    default: 10
    description: Number of rounds of sampling
  num_threads:
    type: integer
    minimum: 1
    default: 10
    description: Number of threads to use for sampling
  run_single_clone_model:
    type: boolean
    default: false
    description: Whether to run cfclone with additional models including only a single clone and the normal population
  cfclone_use_outlier:
    type: boolean
    default: true
    description: Whether to use outlier model in cfClone

required: [
  "out_dir",
  "pipeline_dir",
  "clone_filter_file",
  "hapclone_data_file",
  "hapclone_results_file",
  "snp_file",
  "coverage",
  "tumour_content",
  "num_model_replicates",
  "clone_prevalences",
]